apiVersion: v1
kind: Secret
metadata:
  name: location-service-secret
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY_ID: QUtJQVlSSDVORkNNREZEN04zT1I=
  AWS_SECRET_ACCESS_KEY: dWlOb1pJbUdxUWhTMjU5MkdJam5ublBmVnB2dTdGVUFrOG82WVlGQg==
  AWS_PLACE_INDEX: UGxhY2UtSW5kZXgtMQ==
  AWS_ROUTE_CALCULATOR: Um91dGUtQ2FsY3VsYXRvci0x
  JWT_SECRET: bG9jYXRpb24tc2VydmljZS1qd3Qtc2VjcmV0LWtleS0xMjM0NTY=
